import streamlit as st
import requests
import io
from PIL import Image
import time

# 1. Page Configuration
st.set_page_config(page_title="Patna AI Studio Pro", layout="wide", page_icon="🏙️")

# 2. Session State (Trial and Unlock Logic)
if 'counter' not in st.session_state:
    st.session_state.counter = 0
if 'unlocked' not in st.session_state:
    st.session_state.unlocked = False

# 3. Sidebar UI
with st.sidebar:
    st.title("🏙️ Patna AI Studio Pro")
    st.markdown("---")
    menu = st.radio("🛠️ Choose Service", ["🎨 Image Generator"]) 
    
    st.metric("Daily Trials", f"{st.session_state.counter}/5")
    
    if st.session_state.counter >= 5 and not st.session_state.unlocked:
        st.warning("🚫 Trial Limit Reached!")
        st.link_button("📺 Subscribe YouTube", "https://www.youtube.com/@mukundjha222")
        st.link_button("💙 Follow Facebook", "https://www.facebook.com/share/1Cr1P4ENWW/")
        if st.button("🔓 Unlock Now"):
            st.session_state.unlocked = True
            st.success("Pro Features Unlocked!")
            st.rerun()

# 4. Pro Prompt Function (Hindi/English Translation)
def translate_to_pro_prompt(text):
    try:
        url = f"https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q={text}"
        r = requests.get(url, timeout=10)
        eng_text = r.json()[0][0][0]
        # Adding Quality Keywords
        return f"{eng_text}, highly detailed, 8k resolution, cinematic lighting, masterpiece, professional photography"
    except:
        return text

# 5. Main Logic
if menu == "🎨 Image Generator":
    st.header("🎨 Professional AI Image Studio")
    user_input = st.text_area("What's in your mind? (Hindi/English):", 
                             placeholder="Ek ladka Patna Junction ke bahar khada hai...")
    
    if st.button("🚀 Generate", type="primary"):
        if user_input:
            with st.spinner("🧠 AI is designing your masterpiece..."):
                final_prompt = translate_to_pro_prompt(user_input)
                st.caption(f"✨ **Pro Prompt:** {final_prompt}")
                
                # Image API (Fast & Professional)
                img_url = f"https://image.pollinations.ai/prompt/{final_prompt.replace(' ', '%20')}?width=1024&height=1024&seed={int(time.time())}&nologo=true"
                
                try:
                    res = requests.get(img_url, timeout=30)
                    img = Image.open(io.BytesIO(res.content))
                    
                    # Display & Download
                    st.image(img, caption="Generated by Patna AI Studio", use_container_width=True)
                    
                    buf = io.BytesIO()
                    img.save(buf, format="PNG")
                    st.download_button("📥 Download HD Photo", buf.getvalue(), "patna_ai_studio.png", "image/png")
                    
                    st.session_state.counter += 1
                    st.balloons() 
                except:
                    st.error("API Error! Please check your internet or try again.")
        else:
            st.warning("Kripya kuch likhein!")

# 6. Footer (Fixed Syntax)
st.markdown("---")
st.markdown("<center><b>Patna AI Studio Pro - Bihar's First AI Platform 🚀</b></center>", unsafe_allow_html=True)
